### ISSUE TITLE
Feature: Landing Page

### ISSUE THREAD

**Issue by attilacsanyi** [unixsocial/unix#17]
**Describe the new feature**
Let's add the following contents to the landing page (`unixsocial.com/`):

1. Right top corner has an [X icon](https://lucide.dev/icons/x) which does a redirect to **Blog page** on click
2. Logo in the middle _(add to the `asset/images` or `public/images` folder which is part of prod)_
3. Large primary button with text: "Check it out" which does a redirect to **Blog page** on click
4. Wide Radix Wallet Connect button (use TailwindCSS css variable set: `[--radix-connect-button-width:100px]`)
5. Add the social icons and open each social platform in a new tab using links defined in the `README.md`
_(lets discuss how we got those logos as [Lucide React Icons](https://lucide.dev/) has not supported all of them)_
   1. X
   2. Telegram
   3. Discord
   4. Tik-tok
   6. Instagram

**Where the feature should be placed**
under the base url `/` within landing page

**Sketches**
Video description has been provided via Telegram
<img src="https://github.com/unixsocial/unix/assets/2144794/5ed32e85-b0bc-4b5b-8e99-37437c539aaa" width="500px" />

**Additional context**
Has dependency on #13 #24

**Comment by uniscinft** [comment]
Instead of a basic footer we will create an easy to understand entry page.
Video description on Telegram.

**Comment by attilacsanyi** [comment]
@uniscinft I have some further questions:

1. I assume we need to use the **X instead of Twitter**
2. If you prefer the dark blue _(#141234)_ as the dark background variant instead of black I can align the theme globally. You can play with colors which you like switching light-dark mode. We need colors of both theme. _(The #36d1dc is already the primary color for the dark theme)_
3. Theme-wise we might use a bit different colors due to Shadcn design. So you can pick primary or secondary which has unique background, or one of the followings, but we can play which looks best once the code there:
<img src="https://github.com/unixsocial/unix/assets/2144794/e62e8ff2-ad84-4e29-a203-8195fd497b70" width="200px" />

**Comment by uniscinft** [comment]
i. Correct, we will use X instead of Twitter
ii. I would prefer dark blue (#141234) as our main (dark) layout, and a white as light layout.
iii. Primary is perfect (#36d1dc) for buttons, letters, etc.

**Comment by AhsenRiaz** [comment]
@attilacsanyi @uniscinft  I have some questions. 

1. Where would the Theme Setter menu be placed
2. Is the Logo going to be placed below the header in the middle of the screen

**Comment by attilacsanyi** [comment]
@AhsenRiaz if @uniscinft agree on common header then follow my [suggestion](https://discord.com/channels/@me/1141024148303392798/1151912667662000241):

1. create `app/src/layout/header.tsx` common header component for the app
1. header should look the same as in `blog-header.tsx`, but with logo on the left _(radix, theme toggler on the right)_
1. define the header structure above the `<Outlet />`

_If more question then discuss on that relevant tech debt issue. THX_

**Comment by attilacsanyi** [comment]
@AhsenRiaz as we discussed [here](https://discord.com/channels/@me/1141024148303392798/1151928747109388289) not use common header, so Landing (entry page is so unique, just define with TailwindCSS in it `feature/landing` module.

**Comment by attilacsanyi** [comment]
@AhsenRiaz Did you found any alternative so far? In my past project I use font-awesome social icons, however we not need here. Those social sites has **free logo designs** we need to just grab then from the internet. Be sure to use web optimised format like `webp` or `avif` thx.

Please **attach the relevant logo links to this issue** below, thanks

**Comment by AhsenRiaz** [comment]
@attilacsanyi  These are the relevant logos I have downloaded in the **webp** format to use. Let me know if there's anything to be changed.

Twitter-X: https://logowik.com/twitter-x-icon-logo-vector-59294.html

Discord: https://www.liblogo.com/lib/discord-logo.html

Telegram: https://www.liblogo.com/lib/the-telegram-logo.html

TikTok: https://www.liblogo.com/lib/tiktok-logo.html

Instagram: https://www.liblogo.com/preview/

**Comment by attilacsanyi** [comment]
@AhsenRiaz cannot see those images, you can link it via url's. Please ask @uniscinft about which type of **logo** he wants as some logo is **colourful** another can be **monochrome**. Thanks.

**Comment by AhsenRiaz** [comment]
@attilacsanyi Can I convert PNG logos to Webp?

**Comment by uniscinft** [comment]
Lets go for monochrome signs fitting our UI colors. Thanks!

**Comment by attilacsanyi** [comment]
> @attilacsanyi Can I convert PNG logos to Webp? 

Most of them are available as well, use those first. Yes webp can be converted as most CDNs have image api for that. Thx

**Comment by attilacsanyi** [comment]
Finished first review @AhsenRiaz I added comments, ping me if something is not clear thanks.

**Comment by attilacsanyi** [comment]
a heads up that the **blue** I use from the logo seems not good from accessibility point of view:
here is the **light variation** of landing, i also feel maybe remaining colours for **social icons** might need to also be aligned:

<img src="https://github.com/unixsocial/unix/assets/2144794/d4faa7ba-deef-4c4d-9d3f-7df6ffdc58b4" width="300px"/>



![Image](https://github.com/unixsocial/unix/assets/2144794/a6020534-dd76-4a01-8394-a352d70567a1)

**Comment by attilacsanyi** [comment]
I found the official branding SVG's which are the best @AhsenRiaz 

1. [Twitter-X](https://about.twitter.com/en/who-we-are/brand-toolkit)
1. [Discord](https://discord.com/branding)
1. [Telegram](https://telegram.org/tour/screenshots)
1. [TikTok](https://tiktokbrandbook.com/d/HhXfjVK1Poj9/brand#/basics/logo/primary-logo)
1. [Instagram](https://about.meta.com/brand/resources/instagram/instagram-brand/)

I propose this improvement on the landing @ahsenr @cala.xrd to stick to our theming guide, I use original branding SVG's from their site:


<img src="https://github.com/unixsocial/unix/assets/2144794/231d6c92-828d-4f7a-b62c-94b948967467" width="200px"/>
<img src="https://github.com/unixsocial/unix/assets/2144794/e8b92718-3f10-4e50-aefe-528faf3a5f52" width="200px"/>
