### ISSUE TITLE
Feature: Terms and conditions link

### ISSUE THREAD

**Issue by attilacsanyi** [unixsocial/unix#39]
**Describe the new feature**
1. We need a **link open in new tab to [terms and conditions](https://docs.google.com/document/u/1/d/e/2PACX-1vS4gvFAMZwOzGamVySGSFI6IDHkQRfIIiE1TGcqX1256mGiTQk1GNt68X36hoJpUA/pub)** [document](https://docs.google.com/document/d/1_Z1kExGsF8GprdoySKFgDEWg8C4vC2ym/edit?usp=sharing&ouid=107813190147648733310&rtpof=true&sd=true) shared in our Google Drive
1. Please show **only X and Telegram** on Landing for our social channels _(comment out the rest for now)_

**Where the feature should be placed**
On the Landing page under socials and **center aligned**

**Expected behaviour**
Written document about our terms in one page which can be updated in Google Drive as needed

**Additional context**
Later if needed can be externalised into a CMS so product owner or sales can edit anytime without new development. _([Contentful](https://contentful.com) is one of them)_

**Comment by uniscinft** [comment]
Terms and Conditions have been provided via Discord. Please use the document provided. After loging in and creating a user badge, users have to understand and accept the Unix User Agreement otherwise a badge can't be created (checkmark).

**Comment by attilacsanyi** [comment]
@uniscinft thanks please create a **new issue** and link to the [main ticket ](https://github.com/unixsocial/unix/issues/37) **under point 5.** similar as I started. Thanks

**Comment by uniscinft** [comment]
Done @attilacsanyi 
https://github.com/orgs/unixsocial/projects/3/views/1?pane=issue&itemId=39043041

**Comment by attilacsanyi** [comment]
Great so I am moving to ready for development. 👌
