### ISSUE TITLE
Task: user profile for creating user badge

### ISSUE THREAD

**Issue by uniscinft** [unixsocial/unix#45]
**Describe the new feature**
As a user I should be able to create any number of Unix User badge associated to any of my shared accounts in my profile.

1. new user should have a profile, visible on the blog header
1. if no profile then we need to offer to create a new profile 
1. profile should display existing profiles _(user badges)_ so user can select the active one 
1. profile should allow to create more profiles _(user badge)_
1. on new profile creation an account selection should be rendered if user shared more than one account on login
1. on each profile creation the user should be above 18 and accept terms and conditions _(checkboxes needs to be ticked)_
1. terms and conditions will be a link to a shared Google Drive document open in new tab

**Where the feature should be placed**
In the `blog` page header always visible

**Comment by attilacsanyi** [comment]
Demonstrate how **Unix in this early stage can show the available tokens**:
![Image](https://github.com/unixsocial/unix/assets/2144794/0487eab7-1d38-427a-8372-00332bcb888f)


**First version of login/signup flow** chart:
![Image](https://github.com/unixsocial/unix/assets/2144794/1066d377-f0e9-489e-a323-48ef9f11b8ef)
