### ISSUE TITLE
Feature: Authentication implementation with ROLA

### ISSUE THREAD

**Issue by uniscinft** [unixsocial/unix#6]
Requirements:
1. Implement the Radix connect with **Persona** using **exactly one account with username**
2. Authentication implementation with ROLA using a [Deno](https://deno.com/) and [Oak framework](https://deno.land/x/oak@v12.6.1)
3. Deployed apis using https://api.unixsocial.com/

Useful docs:
1. [ROLA docs](https://docs-babylon.radixdlt.com/main/frontend/rola.html#_uses_of_rola)
2. [ROLA example](https://github.com/radixdlt/rola/tree/main/examples/typescript-full-stack)

**Comment by attilacsanyi** [comment]
[Response from Radix Team](https://discord.com/channels/417762285172555786/1151055875126067221/1151075700917411920) @uniscinft 


![Image](https://github.com/unixsocial/unix/assets/2144794/3de52578-8206-4c7f-9741-faf7464b1510)

**Comment by attilacsanyi** [comment]
[Lighthouse report](https://developer.chrome.com/docs/lighthouse/overview/) checks also added, so we can keep the perf under control release by release

```
    performance = 0.9
    accessibility = 0.8
    best-practices = 1
    seo = 1
    # pwa - this is coming to have native app like feel in browsers
```

See: [PWA](https://web.dev/progressive-web-apps/) for more details


![Image](https://github.com/unixsocial/unix/assets/2144794/b4b1b54a-ef4f-4709-bb19-729823fbffae)

**Comment by attilacsanyi** [comment]
We need to decide which **backend tech** we add as we need this to ROLA *([challenges store](https://github.com/radixdlt/rola/blob/main/examples/typescript-full-stack/apps/server/src/index.ts#L14))*.
I played with **Netlify edge functions (deno), however that is not for stateful logic I suppose**

So we need something like Express / Deno+Oak / [Trpc](https://trpc.io/) @ahsenr _(fastify, etc)_ to implement the endpoints which is called from our React / auth module when authenticate with Radix Connect.

Trpc is good due to strong typing between client and server.

_Are you familiar with any of these?_

**Comment by AhsenRiaz** [comment]
Yes, I'm familiar with ExpressJs and somehow a bit familiar with Trpc too, did a small development on it quite a long time ago.

**Comment by attilacsanyi** [comment]
Thanks, TRPC changed a lot since then I guess. We need to think about the deployment as well so still thinking Deno (Netlify) vs Express.
Depends on CI/CD configuration as well.

**Comment by attilacsanyi** [comment]
Picked the **Deno approach** with **Oak** for now, deployed here: https://unix-api.deno.dev/status

**Comment by attilacsanyi** [comment]
I setup the custom domain for Deno:
![Image](https://github.com/unixsocial/unix/assets/2144794/cf4209fa-e2dc-4bbe-aee6-a22750279a61)

Relevant [Netlify DNS entries](https://app.netlify.com/teams/unixsocial/dns/unixsocial.com):
![Image](https://github.com/unixsocial/unix/assets/2144794/68e4899b-c337-4141-a30d-00ef825603ee)

**Comment by attilacsanyi** [comment]
API has a default route point to `status` endpoint retrieving the followings ([Deno environment variables](https://docs.deno.com/deploy/manual/environment-variables#preset-variables)):

```json
{
  "status": "OK",
  "denoRegion": "europe-central2",
  "denoDeploymentId": "q0sjtczsp96q"
}
```

**Comment by uniscinft** [comment]
Works perfectly

{"status":"OK","denoRegion":"europe-west6","denoDeploymentId":"q0sjtczsp96q"}

**Comment by attilacsanyi** [comment]
https://dev-api.unixsocial.com/ is up and running

I setup the [custom domain for Deno](https://docs.deno.com/deploy/manual/custom-domains):
![Image](https://github.com/unixsocial/unix/assets/2144794/00f17da9-0be8-4832-a94f-61a80bafa031)

Relevant [Netlify DNS entries](https://app.netlify.com/teams/unixsocial/dns/unixsocial.com):
![Image](https://github.com/unixsocial/unix/assets/2144794/80878a7f-1ce7-4dea-8610-8ab0d113a4a7)
